# -*- coding: utf-8 -*-
"""sample code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t4fgAuEHJ2UEvAi3OYqHrMVRSUYKIzry
"""

word = input("Enter a Word : ")
word = word.casefold()
reversed_word = word[::-1]

if word == reversed_word:
  print("This Word Is A Palindrome")

else:
  print("This Word Is Not A Palindrome")